project:
  type: book
  output-dir: docs

book:
  title: "Reproducible Publications"

  # https://quarto.org/docs/journals/authors.html#author-metadata
  author:
    - name: John Doe
      orcid: 0000-1111-2222-3333
      corresponding: true
      affiliations:
        - id: doe
          name: John Doe Center for Technology, John Doe University, Doetown, Germany.
    - name: Jane Roe
      orcid: 0000-2222-3333-4444
      affiliations:
        - ref: doe
        - id: Roe
          name: Institute of Technology, John Doe University, Doetown, Germany.

  chapters:
    - index.qmd

bibliography: meta/references.bib
csl: meta/ios-press-books.csl

format:
 docx:
  toc: true
 pdf:
  toc: true
  latex-engine: xelatex


## https://quarto.org/docs/reference/formats/opml.html#execution
execute:
  echo: false
  message: false
  warning: false
  include: false
  error: true


## https://quarto.org/docs/authoring/cross-references.html#titles
crossref:
  fig-title: Figure     # (default is "Figure")
  tbl-title: Table      # (default is "Table")
  # title-delim: —      # (default is ":")
  fig-prefix: Figure    # (default is "Figure")
  tbl-prefix: Table     # (default is "Table")
  ref-hyperlink: true   # (default is true)
